on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: "Tag (z. B. v10.0.0)"
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # nötig zum Taggen

      - name: Set Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.versionTag }}
          git push origin ${{ github.event.inputs.versionTag }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.versionTag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
